=== webmozart/sulu/src/Sulu/Component/Webspace/Loader/schema/webspace/webspace-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/webspace/webspace" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://schemas.sulu.io/webspace/webspace">
    <xs:complexType name="webspaceType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="security" name="security" minOccurs="0" maxOccurs="1"/>
            <xs:element type="localizationsType" name="localizations"/>
            <xs:element type="segmentsType" name="segments" maxOccurs="1" minOccurs="0"/>
            <xs:element type="themeType" name="theme"/>
            <xs:element type="navigationType" name="navigation"/>
            <xs:element type="portalsType" name="portals"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="security">
        <xs:sequence>
            <xs:element type="xs:string" name="system" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="localizationsType">
        <xs:sequence>
            <xs:element type="localizationType" name="localization" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="localizationType" mixed="true">
        <xs:sequence>
            <xs:element type="localizationType" name="localization" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="language" use="required"/>
        <xs:attribute type="xs:string" name="country" use="optional"/>
        <xs:attribute type="xs:boolean" name="default" use="optional"/>
        <xs:attribute type="xs:boolean" name="x-default" use="optional"/>
        <xs:attribute name="shadow" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="auto"/>
                    <xs:enumeration value="none"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="segmentsType">
        <xs:sequence>
            <xs:element type="segmentType" name="segment" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="segmentType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="key" use="optional"/>
                <xs:attribute type="xs:boolean" name="default" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="navigationType">
        <xs:sequence>
            <xs:element type="navigationContextsType" name="contexts" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="navigationContextsType">
        <xs:sequence>
            <xs:element type="navigationContextType" name="context" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="navigationContextType">
        <xs:sequence>
            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

        <xs:attribute name="key" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="langType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" use="required" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="portalsType">
        <xs:sequence>
            <xs:element type="portalType" name="portal" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="portalType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="resource-locatorType" name="resource-locator"/>
            <xs:element type="localizationsType" name="localizations" minOccurs="0" maxOccurs="1"/>
            <xs:element type="environmentsType" name="environments"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="resource-locatorType">
        <xs:sequence>
            <xs:element type="xs:string" name="strategy"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="themeType">
        <xs:sequence>
            <xs:element type="xs:string" name="key"/>
            <xs:element type="defaultTemplatesType" name="default-templates" minOccurs="1" maxOccurs="1"/>
            <xs:element type="errorTemplatesType" name="error-templates" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="defaultTemplatesType">
        <xs:sequence>
            <xs:element type="defaultTemplateType" name="default-template" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="defaultTemplateType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="errorTemplatesType">
        <xs:sequence>
            <xs:element type="errorTemplateType" name="error-template" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="errorTemplateType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="default" type="xs:boolean"/>
                <xs:attribute name="code" type="xs:integer"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="environmentsType">
        <xs:sequence>
            <xs:element type="environmentType" name="environment" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="environmentType">
        <xs:sequence>
            <xs:element type="urlsType" name="urls"/>
            <xs:element type="customUrlsType" name="custom-urls" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="type" use="optional"/>
    </xs:complexType>
    <xs:complexType name="urlsType">
        <xs:sequence>
            <xs:element type="urlType" name="url" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="urlType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="language" use="optional"/>
                <xs:attribute type="xs:string" name="country" use="optional"/>
                <xs:attribute type="xs:string" name="segment" use="optional"/>
                <xs:attribute type="xs:string" name="redirect" use="optional"/>
                <xs:attribute type="xs:boolean" name="main" use="optional"/>
                <xs:attribute type="xs:string" name="analytics-key" use="optional"/>
                <xs:attribute type="xs:boolean" name="custom-url" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="customUrlsType">
        <xs:sequence>
            <xs:element type="xs:string" name="custom-url" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="webspace" type="webspaceType"/>
</xs:schema>

=== webmozart/sulu/src/Sulu/Bundle/CustomUrlBundle/Tests/app/Resources/webspaces/sulu.io.xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.0.xsd">

    <name>Sulu CMF</name>
    <key>sulu_io</key>

    <localizations>
        <localization language="en"/>
        <localization language="de"/>
    </localizations>

    <theme>
        <key>default</key>
        <default-templates>
            <default-template type="page">default</default-template>
            <default-template type="homepage">overview</default-template>
        </default-templates>
    </theme>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="de">Hauptnavigation</title>
                    <title lang="en">Mainnavigation</title>
                </meta>
            </context>
            <context key="footer">
                <meta>
                    <title lang="de">Footernavigation</title>
                    <title lang="en">Footernavigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>Sulu CMF AT</name>
            <key>sulucmf_at</key>
            <resource-locator>
                <strategy>tree</strategy>
            </resource-locator>

            <localizations>
                <localization language="en" default="true" />
                <localization language="de" />
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
                <environment type="test">
                    <urls>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>

=== webmozart/sulu/src/Sulu/Bundle/SnippetBundle/Tests/app/Resources/webspaces/sulu.io.xml
<?xml version="1.0" encoding="utf-8"?>
<webspace xmlns="http://schemas.sulu.io/webspace/webspace"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/webspace/webspace http://schemas.sulu.io/webspace/webspace-1.0.xsd">

    <name>sulu.io</name>
    <key>sulu_io</key>

    <localizations>
        <localization language="en" shadow="auto">
            <localization language="en" country="us" shadow="auto"/>
        </localization>
        <localization language="de">
            <localization language="de" country="at"/>
        </localization>
    </localizations>

    <theme>
        <key>default</key>
        <default-templates>
            <default-template type="page">default</default-template>
            <default-template type="homepage">default</default-template>
        </default-templates>
    </theme>

    <navigation>
        <contexts>
            <context key="main">
                <meta>
                    <title lang="de">Hauptnavigation</title>
                    <title lang="en">Mainnavigation</title>
                </meta>
            </context>
            <context key="footer">
                <meta>
                    <title lang="de">Footernavigation</title>
                    <title lang="en">Footernavigation</title>
                </meta>
            </context>
        </contexts>
    </navigation>

    <portals>
        <portal>
            <name>sulu.io</name>
            <key>sulu_io</key>
            <resource-locator>
                <strategy>tree</strategy>
            </resource-locator>

            <localizations>
                <localization language="en" default="true"/>
                <localization language="de"/>
            </localizations>

            <environments>
                <environment type="prod">
                    <urls>
                        <url language="en">sulu.us</url>
                        <url language="de">www.sulu.io</url>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
                <environment type="stage">
                    <urls>
                        <url>stage.sulu.lo/{localization}</url>
                        <url>sulu.lo/{localization}</url>
                    </urls>
                </environment>
                <environment type="dev">
                    <urls>
                        <url>sulu.lo/{localization}</url>
                        <url language="en">localhost</url>
                    </urls>
                </environment>
            </environments>
        </portal>
    </portals>
</webspace>
